--- #YAML:1.0
name:               Catalyst-Model-DBI
version:            0.23
abstract:           ~
author:
    - Alex Pavlovic (alex.pavlovic@taskforce-1.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:  5.00
    DBI:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
