---
abstract: unknown
author:
  - 'Alex Pavlovic (alex.pavlovic@taskforce-1.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-DBI
no_index:
  directory:
    - t
    - inc
requires:
  Catalyst: 5.00
  DBI: 0
  DBIx::Connector: 0
  MRO::Compat: 0
version: 0.32
